import express from 'express';
import { register, login, updateProfile, me, logout } from '../controllers/authController.js';
import protect from '../middleware/authMiddleware.js';
const router = express.Router();
router.post('/register', register);
router.post('/login', login);
router.post('/logout', logout);
router.get('/me', protect, me);
router.patch('/me', protect, updateProfile);
export default router;
